namespace SwissTimingDisplay.Models
{
    public enum CharCommand : byte
    {
        SOH = 0x01,
        STX = 0x02,
        ETX = 0x03,
        EOT = 0x04,
        HOME = 0x08,
        LF = 0x0A,
        ERP = 0x0C,
        DLE = 0x10,
        DC3 = 0x13,
        DC4 = 0x14,
        SPC = 0x20,
        NNN = 0xF0,
        TTT = 0xF1,
        Rxx = 0xF2,
        Sxx = 0xF3,
        TIME = 0xF4,
        SPEEDSIGN = 0xE0,
        SPEEDTEN = 0xE1,
        SPEEDWHOLE = 0xE2,
        SPEEDDOT = 0xE3,
        SPEEDTENTHS = 0xE4,
        B = (byte)'B',
        I = (byte)'I',
        C = (byte)'C',
        W = (byte)'W',
        S = (byte)'S',
        X = (byte)'X',
        R= (byte)'R',
        O = (byte)'O',
        G = (byte)'G',
        Space = (byte)' ',
        Zero = (byte)'0',
        One = (byte)'1',
        Two = (byte)'2',
        Three = (byte)'3',
        Dot = (byte)'.',
        s = (byte)'s',
        x = (byte)'x',
        plus = (byte)'+',
        minus = (byte)'-',
        d0 = (byte)'0',
        d1 = (byte)'1',
        d2 = (byte)'2',
        d3 = (byte)'3',
        d4 = (byte)'4',
        d5 = (byte)'5',
        d6 = (byte)'6',
        d7 = (byte)'7',
        d8 = (byte)'8',
        d9 = (byte)'9'


    }

}
