using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Threading;

using SwissTimingDisplay.Models;
using SwissTimingDisplay.ViewModels;

namespace SwissTimingDisplay
{
    /// <summary>
    /// Interaction logic for SiriccoWindow.xaml
    /// Nb: Generated by copying WindGaugeWindow
    /// Interpretation of incoming data is different (to be defined)
    /// </summary>
    public partial class SiriccoWindow : Window
    {
        private MainWindow? _mainWindow;
        private readonly MainViewModel _vm;

        private readonly DispatcherTimer _raceTimer;
        private readonly Stopwatch _raceStopwatch = new Stopwatch();
        private bool _SiriccoIsRunning = false;
        private TimeSpan _raceElapsed = TimeSpan.Zero;
        private bool _sendWallClockWhileRunning = false;
        private bool _SiriccoHasStartedSinceReset = false;
        private bool _autoSendInProgress = false;
        private bool _showingLapTime = false;
        private TimeSpan _lapTime = TimeSpan.Zero;
        private bool _isClosing = false;
        private static readonly TimeSpan RaceTimerInterval = TimeSpan.FromMilliseconds(200);
        private readonly DispatcherTimer _lapContinueTimer;

        public SiriccoWindow() : this(MainViewModel.SharedInstance, null)
        {
        }

        public SiriccoWindow(MainViewModel vm, MainWindow mainWindow = null)
        {
            _vm = vm;
            _mainWindow = mainWindow;
            InitializeComponent();
            DataContext = _vm;

            _vm.PropertyChanged += VmOnPropertyChanged;
            _vm.SiriccoDataReceived += VmOnSiriccoDataReceived;

            Loaded += (_, _) => ApplyAnchorLayout();
            SizeChanged += (_, _) => ApplyAnchorLayout();

            _raceTimer = new DispatcherTimer
            {
                Interval = RaceTimerInterval,
            };
            _raceTimer.Tick += (_, _) =>
            {
                if (!_SiriccoIsRunning)
                {
                    return;
                }


                if (_sendWallClockWhileRunning)
                {
                    _vm.TimeInput = DateTime.Now.ToString("HH:mm:ss");
                }
                else
                {
                    if (_showingLapTime)
                    {
                        // Don't update TimeInput when showing lap time
                    }
                    else
                    {
                        _raceElapsed = _raceStopwatch.Elapsed;
                        UpdateTimeInputFromRaceElapsed();
                    }
                }

                if (!_vm.IsConnected)
                {
                    return;
                }

                // Always use the Siricco start command when race timer is running, regardless of combo box selection
                byte[] cmdbytes = null;
                string msg = " Q,001.59,1,00,M,";
                byte cs = 0;
                foreach (char c in msg)
                {
                    cs ^= (byte)c;
                }
                var msgBytes = msg.Select(c => (byte)c).ToArray();
                cmdbytes = new byte[msgBytes.Length + 5];
                cmdbytes[0] = (byte)CharCommand.STX;
                Array.Copy(msgBytes, 0, cmdbytes, 1, msgBytes.Length);
                cmdbytes[msgBytes.Length + 1] = (byte)CharCommand.ETX;
                cmdbytes[msgBytes.Length + 2] = cs;
                cmdbytes[msgBytes.Length + 3] = (byte)CharCommand.CR;
                cmdbytes[msgBytes.Length + 4] = (byte)CharCommand.LF;
                var payload = cmdbytes;
                BeginAutoSend(payload);
            };
            _raceTimer.Start();

            _lapContinueTimer = new DispatcherTimer
            {
                Interval = _vm.LapContinueDelay,
            };
            _lapContinueTimer.Tick += (_, _) =>
            {
                _lapContinueTimer.Stop();
                _showingLapTime = false;
                _raceElapsed = _raceStopwatch.Elapsed;
                UpdateTimeInputFromRaceElapsed();
                _vm.Status = "Race timer resumed (auto-continue).";
                UpdateLapContinueButton();
            };

            UpdateSiriccoStartButtonContent();
            UpdateWallClockEnabledState();
            UpdateNumDigitsEnabledState();
            UpdateSendEnabledState();
            UpdateRaceTimerEnabledState();
            UpdateLapContinueButton();
        }

        private void VmOnPropertyChanged(object? sender, PropertyChangedEventArgs e)
        {
            if (e.PropertyName == nameof(MainViewModel.IsConnected)
                || e.PropertyName == nameof(MainViewModel.SelectedTcpCommand))
            {
                UpdateRaceTimerEnabledState();
                UpdateSendEnabledState();
            }

            if (e.PropertyName == nameof(MainViewModel.AnchorDisplay))
            {
                ApplyAnchorLayout();
            }

            if (e.PropertyName == nameof(MainViewModel.LapContinueDelay))
            {
                _lapContinueTimer.Interval = _vm.LapContinueDelay;
            }
        }

        private void ApplyAnchorLayout()
        {
            if (rightDisplayColumn is null
                || rightSevenSegBorder is null
                || rightSevenSegViewbox is null
                || rightSevenSegContent is null
                || bottomSevenSegBorder is null
                || bottomSevenSegViewbox is null
                || bottomSevenSegContent is null)
            {
                return;
            }

            if (!_vm.AnchorDisplay)
            {
                rightDisplayColumn.Width = new GridLength(0);
                rightSevenSegBorder.Visibility = Visibility.Collapsed;

                bottomSevenSegBorder.Visibility = Visibility.Visible;
                bottomSevenSegBorder.HorizontalAlignment = HorizontalAlignment.Left;
                bottomSevenSegBorder.VerticalAlignment = VerticalAlignment.Top;
                bottomSevenSegViewbox.HorizontalAlignment = HorizontalAlignment.Left;
                bottomSevenSegViewbox.VerticalAlignment = VerticalAlignment.Center;
                bottomSevenSegViewbox.Stretch = Stretch.None;
                bottomSevenSegViewbox.StretchDirection = StretchDirection.Both;
                return;
            }

            Dispatcher.BeginInvoke(() =>
            {
                if (!_vm.AnchorDisplay)
                {
                    return;
                }

                var scaleRight = EvaluateRightAnchorScale();
                var scaleBottom = EvaluateBottomAnchorScale();

                if (scaleRight >= scaleBottom)
                {
                    ShowRightAnchored();
                }
                else
                {
                    ShowBottomAnchored();
                }
            }, DispatcherPriority.Loaded);
        }

        private double EvaluateRightAnchorScale()
        {
            ShowRightAnchored();
            UpdateLayout();
            return ComputeUniformScale(rightSevenSegViewbox, rightSevenSegContent);
        }

        private double EvaluateBottomAnchorScale()
        {
            ShowBottomAnchored();
            UpdateLayout();
            return ComputeUniformScale(bottomSevenSegViewbox, bottomSevenSegContent);
        }

        private void ShowRightAnchored()
        {
            rightDisplayColumn.Width = GridLength.Auto;
            rightSevenSegBorder.Visibility = Visibility.Visible;
            rightSevenSegViewbox.Stretch = Stretch.Uniform;
            rightSevenSegViewbox.StretchDirection = StretchDirection.Both;

            bottomSevenSegBorder.Visibility = Visibility.Collapsed;
        }

        private void ShowBottomAnchored()
        {
            rightDisplayColumn.Width = new GridLength(0);
            rightSevenSegBorder.Visibility = Visibility.Collapsed;

            bottomSevenSegBorder.Visibility = Visibility.Visible;
            bottomSevenSegBorder.HorizontalAlignment = HorizontalAlignment.Stretch;
            bottomSevenSegBorder.VerticalAlignment = VerticalAlignment.Top;
            bottomSevenSegViewbox.HorizontalAlignment = HorizontalAlignment.Center;
            bottomSevenSegViewbox.VerticalAlignment = VerticalAlignment.Top;
            bottomSevenSegViewbox.Stretch = Stretch.Uniform;
            bottomSevenSegViewbox.StretchDirection = StretchDirection.Both;
        }

        private static double ComputeUniformScale(Viewbox viewbox, FrameworkElement child)
        {
            if (viewbox.ActualWidth <= 0 || viewbox.ActualHeight <= 0)
            {
                return 0;
            }

            child.Measure(new Size(double.PositiveInfinity, double.PositiveInfinity));
            var desired = child.DesiredSize;
            if (desired.Width <= 0 || desired.Height <= 0)
            {
                return 0;
            }

            return Math.Min(viewbox.ActualWidth / desired.Width, viewbox.ActualHeight / desired.Height);
        }

        private void UseWallClock_Checked(object sender, RoutedEventArgs e)
        {
            UpdateWallClockEnabledState();
            UpdateNumDigitsEnabledState();
            UpdateSendEnabledState();
        }

        private void UseWallClock_Unchecked(object sender, RoutedEventArgs e)
        {
            UpdateWallClockEnabledState();
            UpdateNumDigitsEnabledState();
            UpdateSendEnabledState();
        }

        private void SiriccoMessageMode_SelectionChanged(object sender, System.Windows.Controls.SelectionChangedEventArgs e)
        {
            if (e.AddedItems.Count > 0 && e.AddedItems[0] is SiriccoMessageModes mode)
            {
                if (mode == SiriccoMessageModes.WindGauge_ReadFrequency)
                {
                    Debug.WriteLine("WindGauge_ReadFrequency mode selected");
                    // Add logic for WindGauge_ReadFrequency mode here
                }
            }
        }

        private void VmOnSiriccoDataReceived(SiriccoData.SiriccoResult? result)
        {
            if (result == null || !result.IsValid)
            {
                Debug.WriteLine($"Invalid Siricco data received: {result?.ErrorMessage}");
                return;
            }

            // Valid Siricco message received
            Debug.WriteLine($"Valid Siricco data received: Speed={result.Speed}, Speed1={result.Speed1}, Speed2={result.Speed2}, Direction={result.Direction}, SpeedUnit={result.SpeedUnit}, Mode={result.Mode}");

            // TODO: Add interpretation logic here when defined
        }

        protected override void OnClosed(EventArgs e)
        {
            _isClosing = true;
            _raceTimer.Stop();
            _lapContinueTimer.Stop();
            _vm.PropertyChanged -= VmOnPropertyChanged;
            _vm.SiriccoDataReceived -= VmOnSiriccoDataReceived;
            // Don't dispose _vm since it's shared
            base.OnClosed(e);
        }

        private async void Siricco_StartButton(object sender, RoutedEventArgs e)
        {
            if (_SiriccoIsRunning)
            {
                _SiriccoIsRunning = false;
                _vm.IsRaceRunning = false;
                _raceStopwatch.Stop();
                _sendWallClockWhileRunning = false;
                _showingLapTime = false;
                _lapTime = TimeSpan.Zero;
                _lapContinueTimer.Stop();
                UpdateTimeInputFromRaceElapsed();
                _vm.Status = "Race timer stopped.";

                UpdateSiriccoStartButtonContent();
                UpdateWallClockEnabledState();
                UpdateNumDigitsEnabledState();
                UpdateSendEnabledState();
                UpdateLapContinueButton();

                return;
            }

            if (_SiriccoHasStartedSinceReset)
            {
                SendCmd(TcpCommand.WindGauge_Reset_Stop_Clear);

                _raceStopwatch.Reset();
                _raceElapsed = TimeSpan.Zero;
                _sendWallClockWhileRunning = false;
                _SiriccoHasStartedSinceReset = false;
                _vm.RaceHasStartedSinceReset = false;
                _showingLapTime = false;
                _lapTime = TimeSpan.Zero;
                _lapContinueTimer.Stop();
                _vm.IsRaceRunning = false;

                // Send clear command to display
                if (_vm.IsConnected)
                {
                    try
                    {
                        var clearCommand = TcpCommandDefinitions.GetPayloadBytes(TcpCommand.Roller_Time_Mode_Clear).ToArray();
                        await _vm.SendRawAsync(clearCommand);
                        _vm.Status = $"Sent {clearCommand.Length} byte(s) to {_vm.ConnectedPortName}.";
                    }
                    catch (Exception ex)
                    {
                        _vm.Status = ex.Message;
                    }
                }

                _vm.TimeInput = string.Empty;
                UpdateTimeInputFromRaceElapsed();
                _vm.Status = "Race timer reset.";

                UpdateSiriccoStartButtonContent();
                UpdateWallClockEnabledState();
                UpdateNumDigitsEnabledState();
                UpdateSendEnabledState();
                UpdateLapContinueButton();

                return;
            }

            _SiriccoIsRunning = true;
            _vm.IsRaceRunning = true;
            SendCmd(TcpCommand.WindGauge_Start_of_Measurement);
            _sendWallClockWhileRunning = _vm.UseWallClockTimeOfDay;
            _SiriccoHasStartedSinceReset = true;
            _vm.RaceHasStartedSinceReset = true;
            _showingLapTime = false;
            _lapTime = TimeSpan.Zero;



            UpdateTimeInputFromRaceElapsed();
            _vm.Status = "Race timer started.";

            UpdateSiriccoStartButtonContent();
            UpdateWallClockEnabledState();
            UpdateNumDigitsEnabledState();
            UpdateSendEnabledState();
            UpdateLapContinueButton();
        }


        private void ResendLastButton_Click(object sender, RoutedEventArgs e)
        {

            SendCmd(TcpCommand.WindGauge_Resend_Latest);
            ForceUiUpdate();
            UpdateSiriccoStartButtonContent();
            UpdateLapContinueButton();
        }

        private void UpdateSiriccoStartButtonContent()
        {
            if (btnSiriccoStart is null)
            {
                return;
            }

            if (_SiriccoIsRunning)
            {
                btnSiriccoStart.Content = "Stop";
                return;
            }

            btnSiriccoStart.Content = _SiriccoHasStartedSinceReset ? "Reset" : "Start";
        }

        private void UpdateLapContinueButton()
        {
            // Resend Last button should always be visible
            if (btnResendLast is not null)
            {
                btnResendLast.Visibility = Visibility.Visible;
                btnResendLast.IsEnabled = !_SiriccoIsRunning;
            }
        }

        private void ForceUiUpdate()
        {
            // Force immediate UI rendering with high priority
            Dispatcher.Invoke(() => { }, DispatcherPriority.Render);
        }

        private void UpdateWallClockEnabledState()
        {
            if (cbUseWallClock is null)
            {
                return;
            }

            if (btnSiriccoStart?.Content is not string content)
            {
                cbUseWallClock.IsEnabled = false;
                return;
            }

            // Enabled only when race timer button is showing "Start".
            cbUseWallClock.IsEnabled = content == "Start";
        }

        private void UpdateNumDigitsEnabledState()
        {
            if (cbNumDigits is null)
            {
                return;
            }

            cbNumDigits.IsEnabled = !_SiriccoIsRunning && !_SiriccoHasStartedSinceReset;
        }

        private void UpdateSendEnabledState()
        {
            if (btnSend is null)
            {
                return;
            }

            // Disable Send after Start has been pressed until Reset returns to Start state.
            btnSend.IsEnabled = true;// _vm.IsConnected && !_raceIsRunning && !_raceHasStartedSinceReset;
        }

        private void UpdateRaceTimerEnabledState()
        {
            if (btnSiriccoStart is null)
            {
                return;
            }

            var enabled = _vm.IsConnected;
            btnSiriccoStart.IsEnabled = enabled;

            if (!enabled && (_SiriccoIsRunning || _SiriccoHasStartedSinceReset))
            {
                ResetRaceTimerState();
            }
        }

        private async void ResetRaceTimerState()
        {
            _SiriccoIsRunning = false;
            _vm.IsRaceRunning = false;
            _raceStopwatch.Reset();
            _raceElapsed = TimeSpan.Zero;
            _sendWallClockWhileRunning = false;
            _SiriccoHasStartedSinceReset = false;
            _vm.RaceHasStartedSinceReset = false;
            _showingLapTime = false;
            _lapTime = TimeSpan.Zero;
            _lapContinueTimer.Stop();

            // Send clear command to display
            if (_vm.IsConnected)
            {
                try
                {
                    var clearCommand = TcpCommandDefinitions.GetPayloadBytes(TcpCommand.Roller_Time_Mode_Clear).ToArray();
                    await _vm.SendRawAsync(clearCommand);
                    _vm.Status = $"Sent {clearCommand.Length} byte(s) to {_vm.ConnectedPortName}.";
                }
                catch (Exception ex)
                {
                    _vm.Status = ex.Message;
                }
            }

            _vm.TimeInput = string.Empty;
            UpdateTimeInputFromRaceElapsed();

            UpdateSiriccoStartButtonContent();
            UpdateWallClockEnabledState();
            UpdateNumDigitsEnabledState();
            UpdateSendEnabledState();
            UpdateLapContinueButton();
        }

        private async void BeginAutoSend(byte[] payload)
        {
            if (_autoSendInProgress || _isClosing)
            {
                return;
            }

            _autoSendInProgress = true;
            try
            {
                if (!_isClosing)
                {
                    await _vm.SendRawAsync(payload);
                }
            }
            catch (Exception ex)
            {
                if (!_isClosing)
                {
                    _vm.Status = ex.Message;
                }
            }
            finally
            {
                _autoSendInProgress = false;
            }
        }

        private void UpdateTimeInputFromRaceElapsed()
        {
            var hours = (int)_raceElapsed.TotalHours;
            var minutes = _raceElapsed.Minutes;
            var seconds = _raceElapsed.Seconds;
            var tenths = _raceElapsed.Milliseconds / 100;
            var hundredths = (_raceElapsed.Milliseconds / 10) % 100;

            if (hours > 0)
            {
                if (hours > 9)
                {
                    hours = 9;
                }

                _vm.TimeInput = $"{hours}:{minutes:00}:{seconds:00}.{tenths}";
                return;
            }

            var totalMinutes = (int)_raceElapsed.TotalMinutes;
            if (totalMinutes > 99)
            {
                totalMinutes = 99;
            }

            _vm.TimeInput = $"{totalMinutes:00}:{seconds:00}.{hundredths:00}";
        }

        private byte[] BuildExpandedPayload(string cmd)
        {
            var xx =  cmd.Select(c => (byte)c).ToArray();
            var x2 = new byte[cmd.Length];
            int i = 0;
            foreach (char c in cmd)
            {
                byte b = (byte)c;
                x2[i++] = b;
                
            }

            return xx;
        }

        private async void SendCmd(TcpCommand cmd)
        {
            if (cmd == TcpCommand.WindGauge_Acquisition_Duration)
            {
                //CharCommand[] cmdx;
                //byte[] cmdbytes = null;
                //if (TcpCommandDefinitions.Commands.TryGetValue(cmd, out var charCommands))
                //{
                //    cmdx = charCommands.ToArray<CharCommand>();
                //    cmdbytes = cmdx.Select(c => (byte)c).ToArray();

                //    if (_vm.IsConnected)
                //    {
                //        var portName = _vm.ConnectedPortName ?? "(unknown)";
                //        var send = MessageBoxResult.Yes;

                //        if (send == MessageBoxResult.Yes)
                //        {
                //            await _vm.SendRawAsync(cmdbytes);
                //            _vm.Status = $"Sent {cmdbytes.Length} byte(s) to {portName}.";


                //        }
                //    }
                //}
            }
            else
            {
                byte[] cmdbytes = null;
                string msg = " Q,001.59,1,00,M,";
                byte cs = 0;
                foreach (char c in msg)
                {
                    cs ^= (byte)c;
                }

                var msgBytes = msg.Select(c => (byte)c).ToArray();
                cmdbytes = new byte[msgBytes.Length + 5];
                cmdbytes[0] = (byte)CharCommand.STX;
                Array.Copy(msgBytes, 0, cmdbytes, 1, msgBytes.Length);
                cmdbytes[msgBytes.Length + 1] = (byte)CharCommand.ETX;
                cmdbytes[msgBytes.Length + 2] = cs;
                cmdbytes[msgBytes.Length + 3] = (byte)CharCommand.CR;
                cmdbytes[msgBytes.Length + 4] = (byte)CharCommand.LF;
                var payload = cmdbytes;

                if (_vm.IsConnected)
                {
                    var portName = _vm.ConnectedPortName ?? "(unknown)";
                    var send = MessageBoxResult.Yes;

                    if (send == MessageBoxResult.Yes)
                    {
                        await _vm.SendRawAsync(cmdbytes);
                        _vm.Status = $"Sent {cmdbytes.Length} byte(s) to {portName}.";
                    }
                }
            }
        }

        private async void ButtonSend_Click(object sender, RoutedEventArgs e)
        {
            // Check if SiriccoMessageMode is WindGauge_ReadFrequency and handle it
            if (_vm.SiriccoMessageMode == SiriccoMessageModes.WindGauge_ReadFrequency)
            {
                HandleWindGaugeReadFrequencySend();
                return;
            }

            int captureTime = 10;

            try
            {
                var cmd = _vm.SelectedTcpCommand;
                // Clear TimeOut on send side if this was a Clear command
                if (cmd == TcpCommand.WindGauge_Reset_CaptureTime)
                {
                    _vm.WindGaugeCaptureCountdown = "10";
                    return;
                }
                CharCommand[] cmdx;
                byte[] cmdbytes = null;
                if (TcpCommandDefinitions.Commands.TryGetValue(cmd, out var charCommands))
                {
                   cmdx = charCommands.ToArray<CharCommand>();
                   cmdbytes = cmdx.Select(c => (byte)c).ToArray();
                }
                else
                {
                    MessageBox.Show(
                        $"No definition for '{cmd}'.",
                        "Payload",
                        MessageBoxButton.OK,
                        MessageBoxImage.Warning);
                    return;
                }


                string originalLiterals = string.Join(", ", charCommands.Select(c => c.ToString()));

                var needsTime = charCommands.Any(c => c == CharCommand.TIME);;

                if (needsTime)
                {

                    if (string.IsNullOrWhiteSpace(_vm.WindGaugeCaptureCountdown))
                    {
                        _vm.WindGaugeCaptureCountdown = "10";
                    }

                    if(int.TryParse(_vm.WindGaugeCaptureCountdown, out int tim))
                    {
                        if ((tim > 0) && (tim <= 100))
                        {
                            captureTime = tim;
                            string num =captureTime.ToString("D2");
                            byte[] numByte = new byte[] { ((byte)num[0]) , ((byte)num[1]) };

                            int timeIndex = Array.IndexOf(cmdbytes, (byte)CharCommand.TIME);
                            if (timeIndex >= 0)
                            {
                                var newCmdBytes = new byte[cmdbytes.Length + 1];
                                Array.Copy(cmdbytes, 0, newCmdBytes, 0, timeIndex);
                                newCmdBytes[timeIndex] = numByte[0];
                                newCmdBytes[timeIndex + 1] = numByte[1];
                                Array.Copy(cmdbytes, timeIndex + 1, newCmdBytes, timeIndex + 2, cmdbytes.Length - timeIndex - 1);
                                cmdbytes = newCmdBytes;
                            }
                        }
                        else
                        {
                            
                        }
                    }             
                }

                var hex = BitConverter.ToString(cmdbytes);

                if (_vm.IsConnected)
                {
                    var portName = _vm.ConnectedPortName ?? "(unknown)";
                    var send = MessageBoxResult.Yes;

                    if (send == MessageBoxResult.Yes)
                    {
                        await _vm.SendRawAsync(cmdbytes);
                        _vm.Status = $"Sent {cmdbytes.Length} byte(s) to {portName}.";


                    }
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    ex.Message,
                    "Error",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
        }

        private async void HandleWindGaugeReadFrequencySend()
        {
            Debug.WriteLine("Handling WindGauge_ReadFrequency send action");
            // TODO: Implement the send logic for WindGauge_ReadFrequency
            // For example:
            // - Send the WindGauge_ReadFrequency TCP command
            // - Configure the serial port for frequency reading mode
            // - Update UI to indicate frequency reading mode is active
        }

        private async void SendClearButton_Click(object sender, RoutedEventArgs e)
        {
            if( _SiriccoIsRunning)
            {
                SendCmd(TcpCommand.WindGauge_Reset_Stop_Clear);

                _SiriccoIsRunning = false;
                _vm.IsRaceRunning = false;
                _SiriccoHasStartedSinceReset = false;
                _vm.RaceHasStartedSinceReset = false;
                
                UpdateSiriccoStartButtonContent();
                UpdateWallClockEnabledState();
                UpdateNumDigitsEnabledState();
                UpdateSendEnabledState();
                UpdateLapContinueButton();
            }

        }

        private void BackToMainButton_Click(object sender, RoutedEventArgs e)
        {
            // Set current window and save state
            _vm.CurrentWindow = MainViewModel.ActiveWindow.Display;
            _vm.ShowWindGaugeWindow = false;

            if (_mainWindow != null)
            {
                _mainWindow.Show();
            }
            else
            {
                _mainWindow = new MainWindow(_vm);
                _mainWindow.Show();
            }
            this.Hide();
        }

        private void ExitButton_Click(object sender, RoutedEventArgs e)
        {
            _vm.BeginShutdown();
            Application.Current.Shutdown();
        }

        private void Window_Closing(object sender, System.ComponentModel.CancelEventArgs e)
        {
            _vm.BeginShutdown();
            Application.Current.Shutdown();
        }
    }
}
